version: "3.9"
services:

  shipper:
    build:
      context: .
      args:
        package: shipper
    image: shipper:latest
    depends_on:
      - receiver
    volumes:
      - ./testdata:/testdata
    command: "--receiver-addr http://receiver:8080 --watch-dirs testdata/dir1,testdata/dir2"

  receiver:
    build:
      context: .
      args:
        package: receiver
    ports:
      - "8080:8080"
    image: receiver:latest
    command: "--addr :8080"
